modid = "manifestation"
book = "hexcasting:thehexbook"
default_lang = "en_us"
default_branch = "main"


resource_dirs = [
    "resources",
    "{$_common.src}/main/resources",
    { path = "{$_common.src}/generated/resources", required = false },
    { modid = "minecraft" },
    { modid = "hexcasting" },
    { modid = "hexdoc" },
]
export_dir = "src/hexdoc_hexintent/_export/generated"

[extra.hexcasting]
_pattern_regex = { "!Raw" = 'registerAction\("(?P<name>[a-zA-Z0-9_\/]+)",\s*"(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+),' }

[[extra.hexcasting.pattern_stubs]]
path = "{$_common.src}/main/kotlin/com/bluup/manifestation/server/ManifestationServer.kt"
regex = "{^_pattern_regex}"

[template]
icon = "../docs/assets/ExampleTeleportMenu.png"
include = [
    "manifestation",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "HexIntent"
author = "withgallantry"
show_landing_text = true

[textures.override."manifestation:blossom_staff"]
texture = "manifestation:textures/item/staffs.png"

[textures.override."manifestation:blossom_staff_2"]
texture = "manifestation:textures/item/staffs_2.png"

[textures.override."manifestation:dark_forest_staff"]
texture = "manifestation:textures/item/staffs.png"

[textures.override."manifestation:dark_forest_staff_2"]
texture = "manifestation:textures/item/staffs_2.png"

[textures.override."manifestation:eclipse_staff"]
texture = "manifestation:textures/item/staffs.png"

[textures.override."manifestation:eclipse_staff_2"]
texture = "manifestation:textures/item/staffs_2.png"

[textures.override."manifestation:end_staff"]
texture = "manifestation:textures/item/staffs.png"

[textures.override."manifestation:end_staff_2"]
texture = "manifestation:textures/item/staffs_2.png"

[textures.override."manifestation:fern_staff"]
texture = "manifestation:textures/item/staffs.png"

[textures.override."manifestation:fern_staff_2"]
texture = "manifestation:textures/item/staffs_2.png"

[textures.override."manifestation:geode_staff"]
texture = "manifestation:textures/item/staffs.png"

[textures.override."manifestation:geode_staff_2"]
texture = "manifestation:textures/item/staffs_2.png"

[textures.override."manifestation:hydra_staff"]
texture = "manifestation:textures/item/staffs.png"

[textures.override."manifestation:hydra_staff_2"]
texture = "manifestation:textures/item/staffs_2.png"

[textures.override."manifestation:light_staff"]
texture = "manifestation:textures/item/staffs.png"

[textures.override."manifestation:light_staff_2"]
texture = "manifestation:textures/item/staffs_2.png"

[textures.override."manifestation:nether_staff"]
texture = "manifestation:textures/item/staffs.png"

[textures.override."manifestation:nether_staff_2"]
texture = "manifestation:textures/item/staffs_2.png"

[textures.override."manifestation:ocean_staff"]
texture = "manifestation:textures/item/staffs.png"

[textures.override."manifestation:ocean_staff_2"]
texture = "manifestation:textures/item/staffs_2.png"

[textures.override."manifestation:penitence_staff"]
texture = "manifestation:textures/item/staffs.png"

[textures.override."manifestation:penitence_staff_2"]
texture = "manifestation:textures/item/staffs_2.png"

[textures.override."manifestation:redstone_staff"]
texture = "manifestation:textures/item/staffs.png"

[textures.override."manifestation:redstone_staff_2"]
texture = "manifestation:textures/item/staffs_2.png"

[textures.override."manifestation:shadow_staff"]
texture = "manifestation:textures/item/staffs.png"

[textures.override."manifestation:shadow_staff_2"]
texture = "manifestation:textures/item/staffs_2.png"

[textures.override."manifestation:totem_staff"]
texture = "manifestation:textures/item/staffs.png"

[textures.override."manifestation:totem_staff_2"]
texture = "manifestation:textures/item/staffs_2.png"

[textures.override."manifestation:wind_staff"]
texture = "manifestation:textures/item/staffs.png"

[textures.override."manifestation:wind_staff_2"]
texture = "manifestation:textures/item/staffs_2.png"

[_common]
src = "../src"

