modid = "manifestation"
book = "hexcasting:thehexbook"
default_lang = "en_us"
default_branch = "main"

resource_dirs = [
    "resources",
    "{$_common.src}/main/resources",
    { path = "{$_common.src}/generated/resources", required = false },
    { modid = "minecraft" },
    { modid = "hexcasting" },
    { modid = "hexdoc" },
]
export_dir = "src/hexdoc_manifestation/_export/generated"

[extra.hexcasting]
_pattern_regex = { "!Raw" = 'registerAction\("(?P<name>[a-zA-Z0-9_\/]+)",\s*"(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+),' }

[[extra.hexcasting.pattern_stubs]]
path = "{$_common.src}/main/kotlin/com/bluup/manifestation/server/ManifestationServer.kt"
regex = "{^_pattern_regex}"

[template]
icon = "../docs/assets/ExampleTeleportMenu.png"
include = [
    "manifestation",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "HexIntent"
author = "withgallantry"
show_landing_text = true

[_common]
src = "../src"
