# This file is auto-generated by hatch-gradle-version.
# Only the value of PY_VERSION is editable. Do not edit other values.
# This does not have to be kept in sync with the version in build.gradle.

PY_VERSION = "1.0.0"
